//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 01:50:10 PM EET 
//


package md.leonis.assistant.domain.xdxf.lousy;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.List;
import java.util.stream.Collectors;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "k", "tr", "value"
})
@XmlRootElement(name = "ar")
public class Ar {

    @XmlAttribute(name = "f")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String f;

    @XmlElement
    protected String k;

    @XmlElement
    protected String tr;

    @XmlMixed
    protected List<String> value;

    public String getF() {
        return f;
    }

    public void setF(String value) {
        this.f = value;
    }

    public String getValue() {
        return String.join("", value).trim();
    }

    public void setValue(List<String> value) {
        this.value = value;
    }

    public String getK() {
        return k;
    }

    public void setK(String k) {
        this.k = k;
    }

    public String getTr() {
        return tr;
    }

    public void setTr(String tr) {
        this.tr = tr;
    }
}
