//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 01:50:10 PM EET 
//


package md.leonis.assistant.domain.xdxf.lousy;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Def }
     * 
     */
    public Def createDef() {
        return new Def();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link Rref }
     * 
     */
    public Rref createRref() {
        return new Rref();
    }

    /**
     * Create an instance of {@link Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link AbrDef }
     * 
     */
    public AbrDef createAbrDef() {
        return new AbrDef();
    }

    /**
     * Create an instance of {@link K }
     * 
     */
    public K createK() {
        return new K();
    }

    /**
     * Create an instance of {@link Abbreviations }
     * 
     */
    public Abbreviations createAbbreviations() {
        return new Abbreviations();
    }

    /**
     * Create an instance of {@link Xdxf }
     * 
     */
    public Xdxf createXdxf() {
        return new Xdxf();
    }

    /**
     * Create an instance of {@link Ar }
     * 
     */
    public Ar createAr() {
        return new Ar();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link Dtrn }
     * 
     */
    public Dtrn createDtrn() {
        return new Dtrn();
    }

    /**
     * Create an instance of {@link C }
     * 
     */
    public C createC() {
        return new C();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link Co }
     * 
     */
    public Co createCo() {
        return new Co();
    }

    /**
     * Create an instance of {@link Abr }
     * 
     */
    public Abr createAbr() {
        return new Abr();
    }

    /**
     * Create an instance of {@link Opt }
     * 
     */
    public Opt createOpt() {
        return new Opt();
    }

    /**
     * Create an instance of {@link Ex }
     * 
     */
    public Ex createEx() {
        return new Ex();
    }

    /**
     * Create an instance of {@link Kref }
     * 
     */
    public Kref createKref() {
        return new Kref();
    }

    /**
     * Create an instance of {@link Iref }
     * 
     */
    public Iref createIref() {
        return new Iref();
    }

    /**
     * Create an instance of {@link Tense }
     * 
     */
    public Tense createTense() {
        return new Tense();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

}
