--liquibase formatted sql

--changeset leonis:1.0.2

CREATE TABLE User.UserWordBank (
    Word NVARCHAR(136) PRIMARY KEY,
    Smoke BOOLEAN DEFAULT FALSE,
    Reading BOOLEAN DEFAULT FALSE,
    Writing BOOLEAN DEFAULT FALSE,
    Smoked BIGINT NOT NULL DEFAULT 0,
    Read BIGINT NOT NULL DEFAULT 0,
    Written BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE User.WordToLearn (
    Word NVARCHAR(136) PRIMARY KEY,
    Smoke BOOLEAN DEFAULT FALSE,
    Reading BOOLEAN DEFAULT FALSE,
    Writing BOOLEAN DEFAULT FALSE,
    Smoked BIGINT NOT NULL DEFAULT 0,
    Read BIGINT NOT NULL DEFAULT 0,
    Written BIGINT NOT NULL DEFAULT 0
);
