//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 02:10:01 PM EET 
//


package md.leonis.assistant.domain.xdxf.strict;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gr",
    "co",
    "defOrDeftext",
    "ex",
    "sr",
    "etm",
    "categ"
})
@XmlRootElement(name = "def")
public class Def {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "cmt")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cmt;
    @XmlAttribute(name = "freq")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String freq;
    protected String gr;
    protected List<Co> co;
    @XmlElements({
        @XmlElement(name = "def", required = true, type = Def.class),
        @XmlElement(name = "deftext", required = true, type = Deftext.class)
    })
    protected List<Object> defOrDeftext;
    protected List<Ex> ex;
    protected Sr sr;
    protected String etm;
    protected List<Categ> categ;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the cmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmt() {
        return cmt;
    }

    /**
     * Sets the value of the cmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmt(String value) {
        this.cmt = value;
    }

    /**
     * Gets the value of the freq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreq() {
        return freq;
    }

    /**
     * Sets the value of the freq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreq(String value) {
        this.freq = value;
    }

    /**
     * Gets the value of the gr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGr() {
        return gr;
    }

    /**
     * Sets the value of the gr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGr(String value) {
        this.gr = value;
    }

    /**
     * Gets the value of the co property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the co property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Co }
     * 
     * 
     */
    public List<Co> getCo() {
        if (co == null) {
            co = new ArrayList<Co>();
        }
        return this.co;
    }

    /**
     * Gets the value of the defOrDeftext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defOrDeftext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefOrDeftext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Def }
     * {@link Deftext }
     * 
     * 
     */
    public List<Object> getDefOrDeftext() {
        if (defOrDeftext == null) {
            defOrDeftext = new ArrayList<Object>();
        }
        return this.defOrDeftext;
    }

    /**
     * Gets the value of the ex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEx().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ex }
     * 
     * 
     */
    public List<Ex> getEx() {
        if (ex == null) {
            ex = new ArrayList<Ex>();
        }
        return this.ex;
    }

    /**
     * Gets the value of the sr property.
     * 
     * @return
     *     possible object is
     *     {@link Sr }
     *     
     */
    public Sr getSr() {
        return sr;
    }

    /**
     * Sets the value of the sr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sr }
     *     
     */
    public void setSr(Sr value) {
        this.sr = value;
    }

    /**
     * Gets the value of the etm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtm() {
        return etm;
    }

    /**
     * Sets the value of the etm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtm(String value) {
        this.etm = value;
    }

    /**
     * Gets the value of the categ property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categ property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCateg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Categ }
     * 
     * 
     */
    public List<Categ> getCateg() {
        if (categ == null) {
            categ = new ArrayList<Categ>();
        }
        return this.categ;
    }

}
