//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.20 at 02:10:01 PM EET 
//


package md.leonis.assistant.domain.xdxf.strict;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metaInfo",
    "lexicon"
})
@XmlRootElement(name = "xdxf")
public class Xdxf {

    @XmlAttribute(name = "format")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String format;
    @XmlAttribute(name = "revision", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String revision;
    @XmlAttribute(name = "lang_from", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String langFrom;
    @XmlAttribute(name = "lang_to", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String langTo;
    @XmlElement(name = "meta_info", required = true)
    protected MetaInfo metaInfo;
    @XmlElement(required = true)
    protected Lexicon lexicon;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        if (format == null) {
            return "logical";
        } else {
            return format;
        }
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the langFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangFrom() {
        return langFrom;
    }

    /**
     * Sets the value of the langFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangFrom(String value) {
        this.langFrom = value;
    }

    /**
     * Gets the value of the langTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangTo() {
        return langTo;
    }

    /**
     * Sets the value of the langTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangTo(String value) {
        this.langTo = value;
    }

    /**
     * Gets the value of the metaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MetaInfo }
     *     
     */
    public MetaInfo getMetaInfo() {
        return metaInfo;
    }

    /**
     * Sets the value of the metaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaInfo }
     *     
     */
    public void setMetaInfo(MetaInfo value) {
        this.metaInfo = value;
    }

    /**
     * Gets the value of the lexicon property.
     * 
     * @return
     *     possible object is
     *     {@link Lexicon }
     *     
     */
    public Lexicon getLexicon() {
        return lexicon;
    }

    /**
     * Sets the value of the lexicon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lexicon }
     *     
     */
    public void setLexicon(Lexicon value) {
        this.lexicon = value;
    }

}
